---
- hosts: all
  sudo: yes
  tasks:
    - name: Copy files NodeJs
      template: src=/usr/local/etc/ansible/desafio/jsFiles/clusters.js dest=/home/ubuntu/desafio/clusters.js
      template: src=/usr/local/etc/ansible/desafio/jsFiles/app.js dest=/home/ubuntu/desafio/app.js
    - name: Copy configuration file nginx
      template: src=/usr/local/etc/ansible/desafio/nginx/default dest=/etc/nginx/sites-available/default
    - name: Copy configuration files apache2
      template: src=/usr/local/etc/ansible/desafio/apache2/000-default.conf dest=/etc/apache2/sites-available/000-default.conf
    - name: Copy configuration files apache2
      template: src=/usr/local/etc/ansible/desafio/apache2/ports.conf dest=/etc/apache2/
